name: common
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
resolution: workspace
environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  flutter: 
    sdk: flutter
  l: ^5.0.1
  collection: any
  uuid: any
  meta: any
  platform_info: ^5.0.0
  latlong2: ^0.9.1
  rxdart: ^0.28.0
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
