name: tools
description: A sample command-line application with basic argument parsing.
version: 0.0.1

environment:
  sdk: ^3.2.3

dependencies:
  args: any
  path: any
  l: any
  http: any
  mime: any
  http_parser: any
  tinygram: any

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
